// Truth or Dare Prompts
const PROMPTS = {
    truth: [
        "What's the worst fashion trend you've ever participated in?",
        "What's the most childish thing you still do?",
        "What's the most embarrassing text you've sent to the wrong person?",
        "What's the laziest thing you've ever done?",
        "If you had to eat one food for the rest of your life, what would it be?",
        "What's your biggest fear that you think is irrational?",
        "What's the most awkward date you've ever been on?",
        "What's your guilty pleasure TV show or movie?",
        "What's the weirdest dream you've ever had?",
        "What's something you've done that you hope your parents never find out about?",
        "What's the most embarrassing thing that's happened to you at school or work?",
        "What's your biggest pet peeve?",
        "If you could swap lives with someone for a day, who would it be?",
        "What's the worst gift you've ever received?",
        "What's your most embarrassing childhood memory?",
        "What's the weirdest thing you've done when you were alone?",
        "What's something you've done that you immediately regretted?",
        "If you could only save one person in this room from a disaster, who would it be?",
        "What's the last lie you told?",
        "What's your biggest insecurity?",
        "What's the most embarrassing thing in your search history?",
        "What's something you've done that you're most proud of?",
        "What's the worst advice you've ever given?",
        "What's the biggest mistake you've made in your life?",
        "What's the strangest place you've fallen asleep?",
        "What's the most expensive thing you've broken?",
        "What's something you've never told anyone in this room?",
        "What's the most trouble you've ever been in?",
        "What's your biggest regret in life so far?",
        "What's the most disgusting habit you have?",
        "What's the weirdest place you've gone to the bathroom?",
        "What's the worst nickname you've ever had?",
        "What's your most embarrassing moment in public?",
        "What's the most illegal thing you've ever done?",
        "What's the weirdest thing you've eaten?",
        "What's your worst habit?",
        "What's the meanest thing you've ever done to someone?",
        "What's the most embarrassing thing in your room?",
        "What's a secret you've kept from your best friend?",
        "What's the most ridiculous thing you've done because you were bored?"
    ],
    dare: [
        "Do your best impression of another player in the room.",
        "Let another player post anything they want on your social media.",
        "Call a random number and sing happy birthday to them.",
        "Do 20 push-ups without stopping.",
        "Let the group go through your phone for 1 minute.",
        "Speak in an accent of the group's choosing for the next 10 minutes.",
        "Text your crush or an ex something the group decides.",
        "Eat a mix of condiments that the group prepares.",
        "Show everyone your camera roll.",
        "Let someone in the group give you a new hairstyle.",
        "Wear your clothes backwards for the rest of the game.",
        "Prank call someone and keep them on the line for at least 2 minutes.",
        "Let someone draw on your face with makeup or a marker.",
        "Show the last five people you texted and what the messages said.",
        "Let the group choose your profile picture for a week.",
        "Do your best dance move in front of everyone.",
        "Speak without closing your mouth for the next 5 minutes.",
        "Try to drink a glass of water while standing on your hands.",
        "Let the group look through your search history.",
        "Tell a story using only sound effects.",
        "Try to make the group laugh within 30 seconds.",
        "Do your best celebrity impression.",
        "Let someone in the group style your hair for the rest of the game.",
        "Try to lick your elbow.",
        "Do an interpretive dance to a song the group chooses.",
        "Show the group your best party trick.",
        "Let each person in the group ask you a question you must answer truthfully.",
        "Swap outfits with the person to your right for the next 15 minutes.",
        "Speak in rhymes for the next 5 minutes.",
        "Let the group create a cocktail of foods or drinks, and you have to consume it.",
        "Do an impression of your favorite movie character.",
        "Let the group send a text to anyone in your phone.",
        "Do your best robot voice for the next 5 minutes.",
        "Try to moonwalk across the room.",
        "Let someone in the group post a status on your social media account.",
        "Sing the chorus of a song the group selects.",
        "Show the most embarrassing photo on your phone.",
        "Speak only in whispers for the next 10 minutes.",
        "Call a friend and tell them an embarrassing story from your past.",
        "Do your best runway walk across the room."
    ]
}; 